name: Update the HIBP breaches index

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download breaches index
        run: |
          curl -sSL -H "User-Agent: haveibeenpwned.watch" \
            https://haveibeenpwned.com/api/v3/breaches \
            -o index.json
          stat --printf="Index file size: %s bytes\n" index.json

      - name: Configure git author
        run: |
          git config user.name "HIBP Update Bot"
          git config user.email "hibp-bot@example.com"

      - name: Commit changes
        run: |
          git add index.json
          git diff --cached --quiet || git commit -m "Updates HIBP breaches index"
      
      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
